### ISSUE TITLE
Have a Latex package of the theme

### ISSUE THREAD

**Issue by omassicot** [coatless/uiucthemes#25]
Markdown is nice but if one wants to write everything in Latex (for instance to benefit from TikZ or other packages, or simply because they'd rather not use markdown) it would be easier if there were a purely Latex package. I am quite clueless about how you implemented the theme in R and markdown, but if it uses Latex as a backbone anyway, should there not be a readily available .sty file to it?

**Comment by cmainov** [comment]
I agree. I searched the repository for any .sty file that could be implemented in LaTeX but came up with nothing. I would like to implement this outside of R Markdown as well using my TeX editor. Any help is appreciated.

**Comment by coatless** [comment]
Thanks for the issue. Sorry I didn't see it sooner.

I spend the majority of my day inside of _R_ or _Python_. So, I'm not as interested in creating, publishing, and maintaining a separate theming package on [CTAN](https://ctan.org/?lang=en) since this solution has worked well for the last 6-8 years. Moreover, there is _nothing_ restricting the use of `TiKZ` code within the existing template. In fact, I would argue it simplifies the markup required for each slide.

That said, I can understand wanting a pure native approach. So, a few quick details:

1. There isn't a `.sty` powering `beamer_illinois` as the theme re-purposes the existing `AnnArbor` theme.
2. The modifications can be found inside of the `.tex` file that is automatically placed alongside each .Rmd document

You can view the .`tex` file here: 

https://github.com/illinois-r/uiucthemes/blob/fcff820a90e44917ed184f97314eb3069024792b/inst/rmarkdown/templates/beamer_illinois/resources/template.tex#L71-L96

**Comment by cmainov** [comment]
Thank you for pointing me to this file. It seems you are correct and it is easy to modify the existing `AnnArbor` theme with the code chunk you highlight from that `.tex` file.
